Fix bug: link errors when --disable-shared is used
Making all in ncmpidiff
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: ./.libs/libncmpidiff_core.a(ncmpidiff_core.o): in function `ncmpidiff_core':
ncmpidiff_core.c:(.text+0xa3): undefined reference to `ncmpi_inq_file_format'
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: ncmpidiff_core.c:(.text+0xbd): undefined reference to `ncmpi_inq_file_format'